// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'group_tasks.dart';
import 'group_tasks_mls.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `check_connection_status`, `default_nip89_client_tag_enabled`, `default_proxy_url`, `get_client`, `group_todos_by_list`, `list_key_from_d_tag`, `normalize_custom_list_id`, `normalize_synced_todos`, `normalize_todo_date_string`, `receive_subscription_events`, `reconnect_with_timeout`, `reconnect`, `send_event_with_result`, `subscribe`, `unsubscribe_all`, `unsubscribe`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ClientMode`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// MLS/NIP-17: listen_key(#p) 宛の sealed event(kind=1059) を差分取得
///
/// - `since` が 0 より大きい場合、そのUNIX秒以降のイベントのみ取得
/// - `timeout_secs` は fetch_events のタイムアウト秒
///
/// NOTE:
/// - subscription_id は空文字で返す（fetch用途のため）。
Future<List<ReceivedEvent>> fetchMlsGroupTodoEventsSince({
  required String listenKey,
  required PlatformInt64 since,
  required BigInt timeoutSecs,
}) => RustLib.instance.api.crateApiFetchMlsGroupTodoEventsSince(
  listenKey: listenKey,
  since: since,
  timeoutSecs: timeoutSecs,
);

/// Phase 8.3: kind:445 + #h フィルタで MLS Group Events を取得（one-shot fetch）
///
/// subscription方式ではなく、直接fetch_events()を使用してより確実に取得する
///
/// - `group_id`: グループID（#h タグの値）
/// - `since`: UNIX秒（0なら全件取得）
/// - `timeout_secs`: タイムアウト秒
Future<List<ReceivedEvent>> fetchMlsGroupEventsByGroupId({
  required String groupId,
  required PlatformInt64 since,
  required BigInt timeoutSecs,
}) =>
    RustLib.instance.api.crateApiFetchMlsGroupEventsByGroupId(groupId: groupId, since: since, timeoutSecs: timeoutSecs);

Future<List<ReceivedEvent>> fetchMlsGroupEventsByGroupIdWithClientId({
  required String groupId,
  required PlatformInt64 since,
  required BigInt timeoutSecs,
  String? clientId,
}) => RustLib.instance.api.crateApiFetchMlsGroupEventsByGroupIdWithClientId(
  groupId: groupId,
  since: since,
  timeoutSecs: timeoutSecs,
  clientId: clientId,
);

Future<List<ReceivedEvent>> fetchMlsGroupTodoEventsSinceWithClientId({
  required String listenKey,
  required PlatformInt64 since,
  required BigInt timeoutSecs,
  String? clientId,
}) => RustLib.instance.api.crateApiFetchMlsGroupTodoEventsSinceWithClientId(
  listenKey: listenKey,
  since: since,
  timeoutSecs: timeoutSecs,
  clientId: clientId,
);

/// WebSocket `User-Agent` on relay connections (issue #130). Call before any `init_nostr_client*`.
Future<void> setRelayWebsocketUserAgent({required String userAgent}) =>
    RustLib.instance.api.crateApiSetRelayWebsocketUserAgent(userAgent: userAgent);

/// Enable/disable NIP-89 `client` tag on published events (issue #131). Default is enabled.
Future<void> setNip89ClientTagEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiSetNip89ClientTagEnabled(enabled: enabled);

/// Nostrクライアントを初期化（hex公開鍵を返す）
/// client_id を指定しない場合はデフォルトクライアントとして保存
Future<String> initNostrClient({required String secretKeyHex, required List<String> relays}) =>
    RustLib.instance.api.crateApiInitNostrClient(secretKeyHex: secretKeyHex, relays: relays);

/// Nostrクライアントを初期化（プロキシオプション付き）
/// 後方互換性のため残す
Future<String> initNostrClientWithProxy({
  required String secretKeyHex,
  required List<String> relays,
  String? proxyUrl,
}) => RustLib.instance.api.crateApiInitNostrClientWithProxy(
  secretKeyHex: secretKeyHex,
  relays: relays,
  proxyUrl: proxyUrl,
);

/// Nostrクライアントを初期化（Torモード指定）
Future<String> initNostrClientWithTorMode({
  required String secretKeyHex,
  required List<String> relays,
  required TorMode torMode,
  String? proxyUrl,
}) => RustLib.instance.api.crateApiInitNostrClientWithTorMode(
  secretKeyHex: secretKeyHex,
  relays: relays,
  torMode: torMode,
  proxyUrl: proxyUrl,
);

/// Nostrクライアントを初期化（client_id指定可能）
Future<String> initNostrClientWithId({
  required String clientId,
  required String secretKeyHex,
  required List<String> relays,
  String? proxyUrl,
}) => RustLib.instance.api.crateApiInitNostrClientWithId(
  clientId: clientId,
  secretKeyHex: secretKeyHex,
  relays: relays,
  proxyUrl: proxyUrl,
);

/// 公開鍵をnpub形式で取得
Future<String> getPublicKeyNpub() => RustLib.instance.api.crateApiGetPublicKeyNpub();

/// 公開鍵をnpub形式で取得（client_id指定可能）
Future<String> getPublicKeyNpubWithClientId({String? clientId}) =>
    RustLib.instance.api.crateApiGetPublicKeyNpubWithClientId(clientId: clientId);

/// 新しい秘密鍵を生成（hex形式）
Future<String> generateSecretKey() => RustLib.instance.api.crateApiGenerateSecretKey();

Future<KeyPair> generateKeypair() => RustLib.instance.api.crateApiGenerateKeypair();

/// 全Todoを同期（Kind 30001 - 新実装）
Future<List<TodoData>> syncTodoList() => RustLib.instance.api.crateApiSyncTodoList();

/// 全Todoを同期（client_id指定可能）
Future<List<TodoData>> syncTodoListWithClientId({String? clientId}) =>
    RustLib.instance.api.crateApiSyncTodoListWithClientId(clientId: clientId);

/// 全Todoを差分同期（Kind 30001）
///
/// - `since`: UNIX秒（0なら全件相当だが、timeout短縮の用途にも使える）
/// - `timeout_secs`: fetch_events のタイムアウト秒
Future<List<TodoData>> syncTodoListSince({required PlatformInt64 since, required BigInt timeoutSecs}) =>
    RustLib.instance.api.crateApiSyncTodoListSince(since: since, timeoutSecs: timeoutSecs);

Future<List<TodoData>> syncTodoListSinceWithClientId({
  required PlatformInt64 since,
  required BigInt timeoutSecs,
  String? clientId,
}) => RustLib.instance.api.crateApiSyncTodoListSinceWithClientId(
  since: since,
  timeoutSecs: timeoutSecs,
  clientId: clientId,
);

/// Todoリストを作成（Kind 30001）
Future<EventSendResult> createTodoList({required List<TodoData> todos}) =>
    RustLib.instance.api.crateApiCreateTodoList(todos: todos);

/// Todoリストを作成（client_id指定可能）
Future<EventSendResult> createTodoListWithClientId({required List<TodoData> todos, String? clientId}) =>
    RustLib.instance.api.crateApiCreateTodoListWithClientId(todos: todos, clientId: clientId);

/// 秘密鍵を暗号化して保存（パスワードベース）
Future<void> saveEncryptedSecretKey({
  required String storagePath,
  required String secretKey,
  required String password,
}) => RustLib.instance.api.crateApiSaveEncryptedSecretKey(
  storagePath: storagePath,
  secretKey: secretKey,
  password: password,
);

/// 暗号化された秘密鍵を読み込み
Future<String> loadEncryptedSecretKey({required String storagePath, required String password}) =>
    RustLib.instance.api.crateApiLoadEncryptedSecretKey(storagePath: storagePath, password: password);

/// 公開鍵を保存（Amber使用時）
Future<void> savePublicKey({required String storagePath, required String publicKey}) =>
    RustLib.instance.api.crateApiSavePublicKey(storagePath: storagePath, publicKey: publicKey);

/// 公開鍵を読み込み
Future<String?> loadPublicKey({required String storagePath}) =>
    RustLib.instance.api.crateApiLoadPublicKey(storagePath: storagePath);

/// 保存された鍵を削除
Future<void> deleteStoredKeys({required String storagePath}) =>
    RustLib.instance.api.crateApiDeleteStoredKeys(storagePath: storagePath);

/// 暗号化された秘密鍵が存在するか確認
Future<bool> hasEncryptedKey({required String storagePath}) =>
    RustLib.instance.api.crateApiHasEncryptedKey(storagePath: storagePath);

/// 公開鍵が存在するか確認
Future<bool> hasPublicKey({required String storagePath}) =>
    RustLib.instance.api.crateApiHasPublicKey(storagePath: storagePath);

/// Amberから受け取った署名済みイベントを検証
Future<bool> verifyAmberSignature({required String eventJson}) =>
    RustLib.instance.api.crateApiVerifyAmberSignature(eventJson: eventJson);

/// 公開鍵のみでNostrクライアントを初期化（Amber使用時）
/// 署名が必要な操作はAmber経由で行う
Future<String> initNostrClientWithPubkey({required String publicKeyHex, required List<String> relays}) =>
    RustLib.instance.api.crateApiInitNostrClientWithPubkey(publicKeyHex: publicKeyHex, relays: relays);

/// Amberモードで初期化（プロキシオプション付き）
/// 後方互換性のため残す
Future<String> initNostrClientWithPubkeyAndProxy({
  required String publicKeyHex,
  required List<String> relays,
  String? proxyUrl,
}) => RustLib.instance.api.crateApiInitNostrClientWithPubkeyAndProxy(
  publicKeyHex: publicKeyHex,
  relays: relays,
  proxyUrl: proxyUrl,
);

/// Amberモードで初期化（Torモード指定）
Future<String> initNostrClientWithPubkeyAndTorMode({
  required String publicKeyHex,
  required List<String> relays,
  required TorMode torMode,
  String? proxyUrl,
}) => RustLib.instance.api.crateApiInitNostrClientWithPubkeyAndTorMode(
  publicKeyHex: publicKeyHex,
  relays: relays,
  torMode: torMode,
  proxyUrl: proxyUrl,
);

/// Amberモードで初期化（client_id指定可能）
Future<String> initNostrClientWithPubkeyAndId({
  required String clientId,
  required String publicKeyHex,
  required List<String> relays,
  String? proxyUrl,
}) => RustLib.instance.api.crateApiInitNostrClientWithPubkeyAndId(
  clientId: clientId,
  publicKeyHex: publicKeyHex,
  relays: relays,
  proxyUrl: proxyUrl,
);

/// Phase 9.1: NIP-17エフェメラル鍵でイベントに署名（秘密鍵はRust内のみ）
///
/// # Parameters
/// - `unsigned_event_json`: 未署名イベントJSON文字列
///
/// # Returns
/// - 署名済みイベントJSON文字列
///
/// # Security
/// - エフェメラル鍵はRust側のスコープ内のみに存在
/// - 署名後に自動的にdrop（メモリクリア）
/// - Flutter側に秘密鍵は一切渡さない
///
/// # Example
/// ```json
/// // Input (unsigned event):
/// {
///   "content": "encrypted_content",
///   "kind": 1059,
///   "tags": [["p", "listen_key"]],
///   "created_at": 1700000000
/// }
///
/// // Output (signed event):
/// {
///   "id": "event_id",
///   "pubkey": "ephemeral_pubkey",  // ← ランダム鍵
///   "created_at": 1700000000,
///   "kind": 1059,
///   "tags": [["p", "listen_key"]],
///   "content": "encrypted_content",
///   "sig": "signature"
/// }
/// ```
Future<String> signEventWithEphemeralKey({required String unsignedEventJson}) =>
    RustLib.instance.api.crateApiSignEventWithEphemeralKey(unsignedEventJson: unsignedEventJson);

/// 署名済みイベントをリレーに送信
Future<EventSendResult> sendSignedEvent({required String eventJson}) =>
    RustLib.instance.api.crateApiSendSignedEvent(eventJson: eventJson);

/// 署名済みイベントをリレーに送信（client_id指定可能）
Future<EventSendResult> sendSignedEventWithClientId({required String eventJson, String? clientId}) =>
    RustLib.instance.api.crateApiSendSignedEventWithClientId(eventJson: eventJson, clientId: clientId);

/// 暗号化済みcontentで未署名Todoリストイベントを作成（Kind 30001 - Amber暗号化済み用）
///
/// # Parameters
/// - `encrypted_content`: Amber暗号化済みのTodoリストJSON
/// - `public_key_hex`: 公開鍵（hex形式）
/// - `list_id`: リスト識別子（None = デフォルトリスト、Some(id) = カスタムリスト）
/// - `list_title`: リストのタイトル（None = デフォルトタイトル使用）
Future<String> createUnsignedEncryptedTodoListEventWithListId({
  required String encryptedContent,
  required String publicKeyHex,
  String? listId,
  String? listTitle,
}) => RustLib.instance.api.crateApiCreateUnsignedEncryptedTodoListEventWithListId(
  encryptedContent: encryptedContent,
  publicKeyHex: publicKeyHex,
  listId: listId,
  listTitle: listTitle,
);

/// 暗号化済みcontentで未署名Todoリストイベントを作成（Kind 30001 - Amber暗号化済み用）
/// デフォルトリスト用の互換性関数
Future<String> createUnsignedEncryptedTodoListEvent({required String encryptedContent, required String publicKeyHex}) =>
    RustLib.instance.api.crateApiCreateUnsignedEncryptedTodoListEvent(
      encryptedContent: encryptedContent,
      publicKeyHex: publicKeyHex,
    );

/// 暗号化済みcontentで未署名Todoイベントを作成（Amber暗号化済み用 - 旧実装）
Future<String> createUnsignedEncryptedTodoEvent({
  required String todoId,
  required String encryptedContent,
  required String publicKeyHex,
}) => RustLib.instance.api.crateApiCreateUnsignedEncryptedTodoEvent(
  todoId: todoId,
  encryptedContent: encryptedContent,
  publicKeyHex: publicKeyHex,
);

Future<List<TodoListName>> fetchTodoListNamesOnly({required String publicKeyHex}) =>
    RustLib.instance.api.crateApiFetchTodoListNamesOnly(publicKeyHex: publicKeyHex);

Future<List<TodoListName>> fetchTodoListNamesOnlyWithClientId({required String publicKeyHex, String? clientId}) =>
    RustLib.instance.api.crateApiFetchTodoListNamesOnlyWithClientId(publicKeyHex: publicKeyHex, clientId: clientId);

Future<List<EncryptedTodoListEvent>> fetchAllEncryptedTodoListsForPubkey({required String publicKeyHex}) =>
    RustLib.instance.api.crateApiFetchAllEncryptedTodoListsForPubkey(publicKeyHex: publicKeyHex);

/// Phase 2: Subscribe版 - EOSE活用による早期終了
///
/// jokyoプロジェクトで実証された最適化手法:
/// - subscribe()でストリーミング受信
/// - EOSE（End of Stored Events）で即座に終了
/// - タイムアウト: 2.5秒（jokyoの最適値）
///
/// 期待効果: 10秒 → 2-3秒（70-80%短縮）
Future<List<EncryptedTodoListEvent>> fetchAllEncryptedTodoListsSubscribeWithClientId({
  required String publicKeyHex,
  String? clientId,
}) => RustLib.instance.api.crateApiFetchAllEncryptedTodoListsSubscribeWithClientId(
  publicKeyHex: publicKeyHex,
  clientId: clientId,
);

/// すべてのTodoリスト（Kind 30001）を差分取得（Amber復号化用）
///
/// - `since` が 0 より大きい場合、そのUNIX秒以降のイベントのみ取得
/// - 取得後、同じ d tag の中で最新（created_at最大）のイベントのみ返す
///
/// 背景復帰/アプリ再起動時に「全履歴fetch」を避けるための軽量API。
Future<List<EncryptedTodoListEvent>> fetchAllEncryptedTodoListsForPubkeySince({
  required String publicKeyHex,
  required PlatformInt64 since,
  required BigInt timeoutSecs,
}) => RustLib.instance.api.crateApiFetchAllEncryptedTodoListsForPubkeySince(
  publicKeyHex: publicKeyHex,
  since: since,
  timeoutSecs: timeoutSecs,
);

/// Phase 2: Subscribe版（差分取得） - EOSE活用による早期終了
///
/// バックグラウンド復帰時の体感改善用
/// タイムアウト短縮: 3秒 → 1.5秒（50%短縮）
Future<List<EncryptedTodoListEvent>> fetchAllEncryptedTodoListsSubscribeSinceWithClientId({
  required String publicKeyHex,
  required PlatformInt64 since,
  required BigInt timeoutSecs,
  String? clientId,
}) => RustLib.instance.api.crateApiFetchAllEncryptedTodoListsSubscribeSinceWithClientId(
  publicKeyHex: publicKeyHex,
  since: since,
  timeoutSecs: timeoutSecs,
  clientId: clientId,
);

Future<List<EncryptedTodoListEvent>> fetchAllEncryptedTodoListsForPubkeySinceWithClientId({
  required String publicKeyHex,
  required PlatformInt64 since,
  required BigInt timeoutSecs,
  String? clientId,
}) => RustLib.instance.api.crateApiFetchAllEncryptedTodoListsForPubkeySinceWithClientId(
  publicKeyHex: publicKeyHex,
  since: since,
  timeoutSecs: timeoutSecs,
  clientId: clientId,
);

Future<List<EncryptedTodoListEvent>> fetchAllEncryptedTodoListsForPubkeyWithClientId({
  required String publicKeyHex,
  String? clientId,
}) => RustLib.instance.api.crateApiFetchAllEncryptedTodoListsForPubkeyWithClientId(
  publicKeyHex: publicKeyHex,
  clientId: clientId,
);

/// すべてのTodoリストのメタデータ（d tag, title）を取得（通常モード用）
Future<List<TodoListMetadata>> fetchAllTodoListMetadata() => RustLib.instance.api.crateApiFetchAllTodoListMetadata();

Future<List<TodoListMetadata>> fetchAllTodoListMetadataWithClientId({String? clientId}) =>
    RustLib.instance.api.crateApiFetchAllTodoListMetadataWithClientId(clientId: clientId);

/// デフォルトTodoリスト（meiso-todos）のみを取得（互換性のため残す）
Future<EncryptedTodoListEvent?> fetchEncryptedTodoListForPubkey({required String publicKeyHex}) =>
    RustLib.instance.api.crateApiFetchEncryptedTodoListForPubkey(publicKeyHex: publicKeyHex);

Future<EncryptedTodoListEvent?> fetchEncryptedTodoListForPubkeyWithClientId({
  required String publicKeyHex,
  String? clientId,
}) => RustLib.instance.api.crateApiFetchEncryptedTodoListForPubkeyWithClientId(
  publicKeyHex: publicKeyHex,
  clientId: clientId,
);

Future<List<EncryptedTodoEvent>> fetchEncryptedTodosForPubkey({required String publicKeyHex}) =>
    RustLib.instance.api.crateApiFetchEncryptedTodosForPubkey(publicKeyHex: publicKeyHex);

Future<List<EncryptedTodoEvent>> fetchEncryptedTodosForPubkeyWithClientId({
  required String publicKeyHex,
  String? clientId,
}) => RustLib.instance.api.crateApiFetchEncryptedTodosForPubkeyWithClientId(
  publicKeyHex: publicKeyHex,
  clientId: clientId,
);

/// npub形式の公開鍵をhex形式に変換
Future<String> npubToHex({required String npub}) => RustLib.instance.api.crateApiNpubToHex(npub: npub);

/// hex形式の公開鍵をnpub形式に変換
Future<String> hexToNpub({required String hex}) => RustLib.instance.api.crateApiHexToNpub(hex: hex);

/// アプリ設定を保存（Kind 30078 - Application-specific data）
Future<EventSendResult> saveAppSettings({required AppSettings settings}) =>
    RustLib.instance.api.crateApiSaveAppSettings(settings: settings);

/// アプリ設定を保存（client_id指定可能）
Future<EventSendResult> saveAppSettingsWithClientId({required AppSettings settings, String? clientId}) =>
    RustLib.instance.api.crateApiSaveAppSettingsWithClientId(settings: settings, clientId: clientId);

/// アプリ設定を同期（Kind 30078）
Future<AppSettings?> syncAppSettings() => RustLib.instance.api.crateApiSyncAppSettings();

/// アプリ設定を同期（client_id指定可能）
Future<AppSettings?> syncAppSettingsWithClientId({String? clientId}) =>
    RustLib.instance.api.crateApiSyncAppSettingsWithClientId(clientId: clientId);

/// 暗号化済みcontentで未署名アプリ設定イベントを作成（Amber暗号化済み用）
Future<String> createUnsignedEncryptedAppSettingsEvent({
  required String encryptedContent,
  required String publicKeyHex,
}) => RustLib.instance.api.crateApiCreateUnsignedEncryptedAppSettingsEvent(
  encryptedContent: encryptedContent,
  publicKeyHex: publicKeyHex,
);

/// 未署名リレーリストイベントを作成（Amber署名用 - NIP-65 Kind 10002）
Future<String> createUnsignedRelayListEvent({required List<String> relays, required String publicKeyHex}) =>
    RustLib.instance.api.crateApiCreateUnsignedRelayListEvent(relays: relays, publicKeyHex: publicKeyHex);

Future<EncryptedAppSettingsEvent?> fetchEncryptedAppSettingsForPubkey({required String publicKeyHex}) =>
    RustLib.instance.api.crateApiFetchEncryptedAppSettingsForPubkey(publicKeyHex: publicKeyHex);

Future<EncryptedAppSettingsEvent?> fetchEncryptedAppSettingsForPubkeyWithClientId({
  required String publicKeyHex,
  String? clientId,
}) => RustLib.instance.api.crateApiFetchEncryptedAppSettingsForPubkeyWithClientId(
  publicKeyHex: publicKeyHex,
  clientId: clientId,
);

/// リレーリストをNostrに保存（Kind 10002 - Relay List Metadata）
Future<EventSendResult> saveRelayList({required List<String> relays}) =>
    RustLib.instance.api.crateApiSaveRelayList(relays: relays);

/// リレーリストをNostrに保存（client_id指定可能）
Future<EventSendResult> saveRelayListWithClientId({required List<String> relays, String? clientId}) =>
    RustLib.instance.api.crateApiSaveRelayListWithClientId(relays: relays, clientId: clientId);

/// リレーリストをNostrから同期（Kind 10002）
Future<List<String>> syncRelayList() => RustLib.instance.api.crateApiSyncRelayList();

/// リレーリストをNostrから同期（client_id指定可能）
Future<List<String>> syncRelayListWithClientId({String? clientId}) =>
    RustLib.instance.api.crateApiSyncRelayListWithClientId(clientId: clientId);

/// リレーリストを動的に更新（リアルタイム反映）
Future<void> updateRelayList({required List<String> relays}) =>
    RustLib.instance.api.crateApiUpdateRelayList(relays: relays);

/// リレーリストを動的に更新（client_id指定可能）
Future<void> updateRelayListWithClientId({required List<String> relays, String? clientId}) =>
    RustLib.instance.api.crateApiUpdateRelayListWithClientId(relays: relays, clientId: clientId);

/// 指定したイベントIDのリストを削除（Kind 5削除イベントを送信）
Future<EventSendResult> deleteEvents({required List<String> eventIds, String? reason}) =>
    RustLib.instance.api.crateApiDeleteEvents(eventIds: eventIds, reason: reason);

/// イベント削除（client_id指定可能）
Future<EventSendResult> deleteEventsWithClientId({required List<String> eventIds, String? reason, String? clientId}) =>
    RustLib.instance.api.crateApiDeleteEventsWithClientId(eventIds: eventIds, reason: reason, clientId: clientId);

/// 削除イベント（Kind 5）を取得し、削除対象のイベントIDとタイムスタンプのリストを返す
///
/// 戻り値: Vec<(event_id, deletion_created_at)>
/// - event_id: 削除対象のイベントID（eタグ）
/// - deletion_created_at: 削除イベント自体のcreated_at（LWW比較用）
Future<List<(String, BigInt)>> fetchDeletionEventsForPubkey({required String publicKeyHex}) =>
    RustLib.instance.api.crateApiFetchDeletionEventsForPubkey(publicKeyHex: publicKeyHex);

Future<List<(String, BigInt)>> fetchDeletionEventsForPubkeyWithClientId({
  required String publicKeyHex,
  String? clientId,
}) => RustLib.instance.api.crateApiFetchDeletionEventsForPubkeyWithClientId(
  publicKeyHex: publicKeyHex,
  clientId: clientId,
);

/// Personal ListのeventIDを検索（d tagから）
///
/// Phase E.6: リスト削除時にeventIDを動的に取得
///
/// 引数:
/// - list_id: カスタムリストのID (例: "abc123")
/// - public_key_hex: ユーザーの公開鍵（hex形式）
///
/// 戻り値:
/// - Ok(Some(event_id)): イベントが見つかった場合
/// - Ok(None): イベントが見つからない場合
/// - Err: エラー
Future<String?> findPersonalListEventId({required String listId, required String publicKeyHex}) =>
    RustLib.instance.api.crateApiFindPersonalListEventId(listId: listId, publicKeyHex: publicKeyHex);

Future<String?> findPersonalListEventIdWithClientId({
  required String listId,
  required String publicKeyHex,
  String? clientId,
}) => RustLib.instance.api.crateApiFindPersonalListEventIdWithClientId(
  listId: listId,
  publicKeyHex: publicKeyHex,
  clientId: clientId,
);

/// Subscriptionを開始（Todo/設定などのリアルタイム更新）
Future<SubscriptionInfo> startSubscription({required String filtersJson}) =>
    RustLib.instance.api.crateApiStartSubscription(filtersJson: filtersJson);

/// Subscriptionを開始（client_id指定可能）
Future<SubscriptionInfo> startSubscriptionWithClientId({required String filtersJson, String? clientId}) =>
    RustLib.instance.api.crateApiStartSubscriptionWithClientId(filtersJson: filtersJson, clientId: clientId);

/// Subscriptionを停止
Future<void> stopSubscription({required String subscriptionId}) =>
    RustLib.instance.api.crateApiStopSubscription(subscriptionId: subscriptionId);

/// Subscriptionを停止（client_id指定可能）
Future<void> stopSubscriptionWithClientId({required String subscriptionId, String? clientId}) =>
    RustLib.instance.api.crateApiStopSubscriptionWithClientId(subscriptionId: subscriptionId, clientId: clientId);

/// すべてのSubscriptionを停止
Future<void> stopAllSubscriptions() => RustLib.instance.api.crateApiStopAllSubscriptions();

/// すべてのSubscriptionを停止（client_id指定可能）
Future<void> stopAllSubscriptionsWithClientId({String? clientId}) =>
    RustLib.instance.api.crateApiStopAllSubscriptionsWithClientId(clientId: clientId);

/// Subscription経由でイベントを受信
/// timeout_ms: タイムアウト（ミリ秒）
Future<List<ReceivedEvent>> receiveSubscriptionEvents({required BigInt timeoutMs}) =>
    RustLib.instance.api.crateApiReceiveSubscriptionEvents(timeoutMs: timeoutMs);

/// Subscription経由でイベントを受信（client_id指定可能）
Future<List<ReceivedEvent>> receiveSubscriptionEventsWithClientId({required BigInt timeoutMs, String? clientId}) =>
    RustLib.instance.api.crateApiReceiveSubscriptionEventsWithClientId(timeoutMs: timeoutMs, clientId: clientId);

/// リレー接続状態をチェック
Future<bool> checkConnectionStatus() => RustLib.instance.api.crateApiCheckConnectionStatus();

/// リレー接続状態をチェック（client_id指定可能）
Future<bool> checkConnectionStatusWithClientId({String? clientId}) =>
    RustLib.instance.api.crateApiCheckConnectionStatusWithClientId(clientId: clientId);

/// リレーに再接続
Future<void> reconnectToRelays() => RustLib.instance.api.crateApiReconnectToRelays();

/// リレーに再接続（client_id指定可能）
Future<void> reconnectToRelaysWithClientId({String? clientId}) =>
    RustLib.instance.api.crateApiReconnectToRelaysWithClientId(clientId: clientId);

/// リレーに再接続（タイムアウト秒を指定）
Future<void> reconnectToRelaysWithTimeout({required BigInt timeoutSecs}) =>
    RustLib.instance.api.crateApiReconnectToRelaysWithTimeout(timeoutSecs: timeoutSecs);

Future<void> reconnectToRelaysWithTimeoutAndClientId({required BigInt timeoutSecs, String? clientId}) =>
    RustLib.instance.api.crateApiReconnectToRelaysWithTimeoutAndClientId(timeoutSecs: timeoutSecs, clientId: clientId);

/// イベントJSONからキャッシュ情報を作成（Event型を使わずに）
Future<CachedEventInfo> createCacheInfo({required String eventJson, required BigInt ttlSeconds}) =>
    RustLib.instance.api.crateApiCreateCacheInfo(eventJson: eventJson, ttlSeconds: ttlSeconds);

/// キャッシュが有効かチェック
Future<bool> isCacheValid({required CachedEventInfo cacheInfo}) =>
    RustLib.instance.api.crateApiIsCacheValid(cacheInfo: cacheInfo);

/// グループタスクリストを暗号化（マルチパーティ暗号化）
///
/// # Parameters
/// - `tasks`: グループタスクのリスト
/// - `group_id`: グループID（UUID）
/// - `group_name`: グループ名
/// - `member_pubkeys`: メンバーの公開鍵リスト（hex形式）
Future<GroupTodoList> encryptGroupTaskList({
  required List<GroupTodoData> tasks,
  required String groupId,
  required String groupName,
  required List<String> memberPubkeys,
}) => RustLib.instance.api.crateApiEncryptGroupTaskList(
  tasks: tasks,
  groupId: groupId,
  groupName: groupName,
  memberPubkeys: memberPubkeys,
);

/// グループタスクリストを復号化
///
/// # Parameters
/// - `group_list`: 暗号化されたグループタスクリスト
Future<List<GroupTodoData>> decryptGroupTaskList({required GroupTodoList groupList}) =>
    RustLib.instance.api.crateApiDecryptGroupTaskList(groupList: groupList);

/// グループにメンバーを追加
///
/// # Parameters
/// - `group_list`: 既存のグループタスクリスト
/// - `new_member_pubkey`: 追加するメンバーの公開鍵（hex形式）
Future<GroupTodoList> addMemberToGroupTaskList({required GroupTodoList groupList, required String newMemberPubkey}) =>
    RustLib.instance.api.crateApiAddMemberToGroupTaskList(groupList: groupList, newMemberPubkey: newMemberPubkey);

/// グループからメンバーを削除（Forward Secrecy: 全体を再暗号化）
///
/// # Parameters
/// - `group_list`: 既存のグループタスクリスト
/// - `member_to_remove`: 削除するメンバーの公開鍵（hex形式）
Future<GroupTodoList> removeMemberFromGroupTaskList({
  required GroupTodoList groupList,
  required String memberToRemove,
}) => RustLib.instance.api.crateApiRemoveMemberFromGroupTaskList(groupList: groupList, memberToRemove: memberToRemove);

/// グループタスクリストをNostrに保存（Kind 30001 - NIP-51）
///
/// # Parameters
/// - `group_list`: 暗号化されたグループタスクリスト
Future<EventSendResult> saveGroupTaskListToNostr({required GroupTodoList groupList}) =>
    RustLib.instance.api.crateApiSaveGroupTaskListToNostr(groupList: groupList);

/// グループタスクリストの未署名イベントを作成（Amberモード用）
///
/// GroupTodoListを受け取り、暗号化済みcontentで未署名イベントJSONを作成
///
/// # Arguments
/// * `group_list_json` - GroupTodoListのJSON文字列（暗号化前）
/// * `encrypted_content` - Amberで暗号化済みのcontent
/// * `public_key_hex` - 作成者の公開鍵（hex）
///
/// # Returns
/// 未署名イベントのJSON文字列
Future<String> createUnsignedGroupTaskListEvent({
  required String groupListJson,
  required String encryptedContent,
  required String publicKeyHex,
}) => RustLib.instance.api.crateApiCreateUnsignedGroupTaskListEvent(
  groupListJson: groupListJson,
  encryptedContent: encryptedContent,
  publicKeyHex: publicKeyHex,
);

/// 公開鍵だけで暗号化されたグループタスクイベントを取得（Amber復号化用）
/// 復号化はAmber側で行うため、暗号化されたままのイベントを返す
Future<List<EncryptedGroupTodoListEvent>> fetchEncryptedGroupTaskListsForPubkey({required String publicKeyHex}) =>
    RustLib.instance.api.crateApiFetchEncryptedGroupTaskListsForPubkey(publicKeyHex: publicKeyHex);

Future<List<EncryptedGroupTodoListEvent>> fetchEncryptedGroupTaskListsForPubkeyWithClientId({
  required String publicKeyHex,
  String? clientId,
}) => RustLib.instance.api.crateApiFetchEncryptedGroupTaskListsForPubkeyWithClientId(
  publicKeyHex: publicKeyHex,
  clientId: clientId,
);

/// タスクデータをAES-256-GCMで暗号化（Amberモード用）
///
/// # Arguments
/// * `tasks_json` - タスクデータのJSON文字列
/// * `aes_key_base64` - base64エンコードされたAES-256鍵（32バイト）
///
/// # Returns
/// base64エンコードされた暗号化データ（ノンス12バイト + 暗号文）
Future<String> encryptGroupDataWithAesKey({required String tasksJson, required String aesKeyBase64}) =>
    RustLib.instance.api.crateApiEncryptGroupDataWithAesKey(tasksJson: tasksJson, aesKeyBase64: aesKeyBase64);

/// AES鍵を使ってグループタスクデータを復号化（Amberモード用）
///
/// Amberで復号化済みのAES鍵を使ってデータを復号化する
///
/// # Arguments
/// * `encrypted_data_base64` - base64エンコードされた暗号化データ
/// * `aes_key_base64` - base64エンコードされたAES鍵（すでに復号化済み）
///
/// # Returns
/// 復号化されたJSON文字列
Future<String> decryptGroupDataWithAesKey({required String encryptedDataBase64, required String aesKeyBase64}) =>
    RustLib.instance.api.crateApiDecryptGroupDataWithAesKey(
      encryptedDataBase64: encryptedDataBase64,
      aesKeyBase64: aesKeyBase64,
    );

/// 自分がメンバーになっているグループタスクリストを取得（非推奨 - Amberモードでは動作しない）
/// 代わりに fetch_encrypted_group_task_lists_for_pubkey を使用してください
Future<List<GroupTodoList>> fetchMyGroupTaskLists() => RustLib.instance.api.crateApiFetchMyGroupTaskLists();

/// MLS: データベース初期化
Future<void> mlsInitDb({required String dbPath, required String nostrId}) =>
    RustLib.instance.api.crateApiMlsInitDb(dbPath: dbPath, nostrId: nostrId);

/// MLS: Export SecretからListen Key取得
Future<String> mlsGetListenKey({required String nostrId, required String groupId}) =>
    RustLib.instance.api.crateApiMlsGetListenKey(nostrId: nostrId, groupId: groupId);

/// NIP-EE: MLS Group Event (kind:445) の content を NIP-44 で暗号化する
///
/// NIP-EE (nips/EE.md) に従い、
/// - exporter_secret(32 bytes, label "nostr") を「秘密鍵」として扱い
/// - そこから導出した公開鍵（= listen key）を「受信者鍵」として扱い
/// - NIP-44(v2) で "MLSMessage(= mls_add_todo の戻り値 hex)" を暗号化する
///
/// Flutter側には exporter_secret を露出させない。
Future<String> mlsEncryptGroupEventContent({
  required String nostrId,
  required String groupId,
  required String mlsMessageHex,
}) => RustLib.instance.api.crateApiMlsEncryptGroupEventContent(
  nostrId: nostrId,
  groupId: groupId,
  mlsMessageHex: mlsMessageHex,
);

/// MLS: TODOグループ作成
Future<Uint8List> mlsCreateTodoGroup({
  required String nostrId,
  required String groupId,
  required String groupName,
  required List<String> keyPackages,
}) => RustLib.instance.api.crateApiMlsCreateTodoGroup(
  nostrId: nostrId,
  groupId: groupId,
  groupName: groupName,
  keyPackages: keyPackages,
);

/// Phase D.8: MLS TODOをグループに追加（暗号化、NIP-EE完全準拠）
///
/// # Arguments
/// * `nostr_id` - ユーザーのNostr公開鍵
/// * `group_id` - グループID
/// * `todo_json` - TODO項目のJSON文字列
/// * `action` - アクション種別 (add | update | delete | toggle | reorder | move)
/// * `todo_id` - TODO固有識別子
///
/// # Returns
/// * 暗号化されたメッセージ（hex）
Future<String> mlsAddTodo({
  required String nostrId,
  required String groupId,
  required String todoJson,
  required String action,
  required String todoId,
}) => RustLib.instance.api.crateApiMlsAddTodo(
  nostrId: nostrId,
  groupId: groupId,
  todoJson: todoJson,
  action: action,
  todoId: todoId,
);

/// Phase D.8: MLS TODOを復号化（NIP-EE完全準拠）
///
/// # Arguments
/// * `nostr_id` - ユーザーのNostr公開鍵
/// * `group_id` - グループID
/// * `encrypted_msg` - Nostrイベントからの暗号化メッセージ（hex）
///
/// # Returns
/// * Tuple (todo_content, action, todo_id, sender_pubkey, listen_key)
///   - Phase 9.1形式: actionとtodo_idは空文字列
///   - Phase D.8形式: 全フィールドに値が入る
Future<(String, String, String, String, String)> mlsDecryptTodo({
  required String nostrId,
  required String groupId,
  required String encryptedMsg,
}) => RustLib.instance.api.crateApiMlsDecryptTodo(nostrId: nostrId, groupId: groupId, encryptedMsg: encryptedMsg);

/// MLS: Key Package作成
Future<KeyPackageResult> mlsCreateKeyPackage({required String nostrId}) =>
    RustLib.instance.api.crateApiMlsCreateKeyPackage(nostrId: nostrId);

/// MLS: グループに参加（Welcome Message使用）
Future<void> mlsJoinGroup({required String nostrId, required String groupId, required List<int> welcomeMsg}) =>
    RustLib.instance.api.crateApiMlsJoinGroup(nostrId: nostrId, groupId: groupId, welcomeMsg: welcomeMsg);

/// MLS SQLite DBをBase64エンコード形式でエクスポート
///
/// Phase 2.5A: Key Package手動バックアップ機能
///
/// ユーザーがアプリ削除前にバックアップを取得できるようにする。
/// エクスポートしたBase64文字列をファイルまたはクリップボードに保存することで、
/// アプリ再インストール後も既存のMLSグループに再参加可能になる。
///
/// # Arguments
/// * `db_path` - MLS SQLite DBのファイルパス
///
/// # Returns
/// * Base64エンコードされたDB内容
///
/// # Error
/// * DBファイルが存在しない場合
/// * ファイル読み込みに失敗した場合
Future<String> exportMlsDatabaseAsBase64({required String dbPath}) =>
    RustLib.instance.api.crateApiExportMlsDatabaseAsBase64(dbPath: dbPath);

/// Base64エンコードされたMLS SQLite DBをインポート
///
/// Phase 2.5A: Key Package手動リストア機能
///
/// バックアップからMLS DBを復元する。
/// 既存のDBがある場合は`.bak`拡張子でバックアップを作成してから上書きする。
///
/// # Arguments
/// * `db_path` - MLS SQLite DBのファイルパス
/// * `base64_data` - Base64エンコードされたDB内容
/// * `nostr_id` - ユーザーの公開鍵（DBリロード用）
///
/// # Returns
/// * 成功時は空文字列
///
/// # Error
/// * Base64デコードに失敗した場合
/// * ファイル書き込みに失敗した場合
/// * DBリロードに失敗した場合
Future<String> importMlsDatabaseFromBase64({
  required String dbPath,
  required String base64Data,
  required String nostrId,
}) =>
    RustLib.instance.api.crateApiImportMlsDatabaseFromBase64(dbPath: dbPath, base64Data: base64Data, nostrId: nostrId);

/// MLS: グループ情報を取得
///
/// グループ名、メンバーリスト、エポックを取得する。
/// Welcome Message処理後、実際のグループ状態をFlutter側に伝搬するために使用。
Future<MlsGroupInfo> mlsGetGroupInfo({required String nostrId, required String groupId}) =>
    RustLib.instance.api.crateApiMlsGetGroupInfo(nostrId: nostrId, groupId: groupId);

/// MLS: Key Package公開イベント作成（Kind 10443 - NIP-EE）
///
/// Key PackageをKind 10443イベントとして公開することで、
/// 他のユーザーがnpubから自動的にKey Packageを取得できるようになる
///
/// # Arguments
/// * `key_package_result` - mlsCreateKeyPackageの結果
/// * `public_key_hex` - ユーザーの公開鍵（hex）
/// * `relays` - Key Packageを公開するリレーのリスト
///
/// # Returns
/// * 未署名イベントJSON（Amber署名用）
Future<String> createUnsignedKeyPackageEvent({
  required KeyPackageResult keyPackageResult,
  required String publicKeyHex,
  required List<String> relays,
}) => RustLib.instance.api.crateApiCreateUnsignedKeyPackageEvent(
  keyPackageResult: keyPackageResult,
  publicKeyHex: publicKeyHex,
  relays: relays,
);

/// MLS: グループ招待を同期（Kind 30078から取得）
///
/// 自分宛のグループ招待イベントを取得する
///
/// # Arguments
/// * `recipient_public_key_hex` - 受信者の公開鍵（hex）
/// * `client_id` - NostrクライアントID（オプション）
///
/// # Returns
/// * グループ招待のJSON配列
Future<String> syncGroupInvitations({required String recipientPublicKeyHex, String? clientId}) =>
    RustLib.instance.api.crateApiSyncGroupInvitations(recipientPublicKeyHex: recipientPublicKeyHex, clientId: clientId);

/// MLS: グループ招待イベント作成（Kind 30078 + NIP-44）
///
/// グループ招待通知をKind 30078イベントとして作成（未署名）
/// 受信者の公開鍵でNIP-44暗号化される
///
/// # Arguments
/// * `sender_public_key_hex` - 送信者の公開鍵（hex）
/// * `recipient_npub` - 受信者のnpub
/// * `group_id` - グループID
/// * `group_name` - グループ名
/// * `welcome_msg_base64` - Welcome Message（base64エンコード済み）
/// * `inviter_name` - 招待者の名前（オプション）
///
/// # Returns
/// * 未署名イベントJSON（Amber署名用）
Future<String> createUnsignedGroupInvitationEvent({
  required String senderPublicKeyHex,
  required String recipientNpub,
  required String groupId,
  required String groupName,
  required String welcomeMsgBase64,
  String? inviterName,
}) => RustLib.instance.api.crateApiCreateUnsignedGroupInvitationEvent(
  senderPublicKeyHex: senderPublicKeyHex,
  recipientNpub: recipientNpub,
  groupId: groupId,
  groupName: groupName,
  welcomeMsgBase64: welcomeMsgBase64,
  inviterName: inviterName,
);

/// MLS: npubからKey Packageを取得（Kind 10443）
///
/// 指定したnpubのユーザーが公開しているKey Packageを取得する
///
/// # Arguments
/// * `npub` - 取得対象ユーザーのnpub（bech32形式）
///
/// # Returns
/// * Key Package（hex文字列）
Future<String> fetchKeyPackageByNpub({required String npub}) =>
    RustLib.instance.api.crateApiFetchKeyPackageByNpub(npub: npub);

/// MLS: npubからKey Packageを取得（client_id指定可能）
Future<String> fetchKeyPackageByNpubWithClientId({required String npub, String? clientId}) =>
    RustLib.instance.api.crateApiFetchKeyPackageByNpubWithClientId(npub: npub, clientId: clientId);

/// Kind 10063 (BUD-03 / NIP-B7) からBlossomサーバーリストを取得
Future<List<String>> fetchBlossomServerList() => RustLib.instance.api.crateApiFetchBlossomServerList();

Future<List<String>> fetchBlossomServerListWithClientId({String? clientId}) =>
    RustLib.instance.api.crateApiFetchBlossomServerListWithClientId(clientId: clientId);

/// Kind 24242 Blossom auth event を作成・署名して返す（秘密鍵モード）
///
/// Amber モードでは `create_unsigned_blossom_auth_event` で未署名JSONを取得し、
/// Amber 側で署名後に base64 エンコードして Authorization ヘッダーに使用する。
Future<String> signBlossomAuthEvent({required String sha256Hex, required PlatformInt64 fileSize}) =>
    RustLib.instance.api.crateApiSignBlossomAuthEvent(sha256Hex: sha256Hex, fileSize: fileSize);

Future<String> signBlossomAuthEventWithClientId({
  required String sha256Hex,
  required PlatformInt64 fileSize,
  String? clientId,
}) => RustLib.instance.api.crateApiSignBlossomAuthEventWithClientId(
  sha256Hex: sha256Hex,
  fileSize: fileSize,
  clientId: clientId,
);

/// Kind 24242 未署名イベントを作成（Amber 署名用）
Future<String> createUnsignedBlossomAuthEvent({
  required String sha256Hex,
  required PlatformInt64 fileSize,
  required String publicKeyHex,
}) => RustLib.instance.api.crateApiCreateUnsignedBlossomAuthEvent(
  sha256Hex: sha256Hex,
  fileSize: fileSize,
  publicKeyHex: publicKeyHex,
);

/// Kind 27235 NIP-98 HTTP auth event を作成・署名して返す（秘密鍵モード）
///
/// Amber モードでは `create_unsigned_nip98_auth_event` で未署名JSONを取得する。
Future<String> signNip98AuthEvent({required String url, required String method}) =>
    RustLib.instance.api.crateApiSignNip98AuthEvent(url: url, method: method);

Future<String> signNip98AuthEventWithClientId({required String url, required String method, String? clientId}) =>
    RustLib.instance.api.crateApiSignNip98AuthEventWithClientId(url: url, method: method, clientId: clientId);

/// Kind 27235 未署名イベントを作成（Amber 署名用）
Future<String> createUnsignedNip98AuthEvent({
  required String url,
  required String method,
  required String publicKeyHex,
}) => RustLib.instance.api.crateApiCreateUnsignedNip98AuthEvent(url: url, method: method, publicKeyHex: publicKeyHex);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MeisoNostrClient>>
abstract class MeisoNostrClient implements RustOpaqueInterface {
  /// アプリ設定をNostrイベントとして作成（Kind 30078 - NIP-78）
  Future<EventSendResult> createAppSettings({required AppSettings settings});

  /// TodoリストをNostrイベントとして作成（Kind 30001 - NIP-51 Bookmark List）
  /// リストごとに個別のイベントを作成
  Future<EventSendResult> createTodoList({required List<TodoData> todos});

  /// 秘密鍵が利用可能かチェック
  Future<bool> hasSecretKey();

  /// クライアントモードを取得
  Future<void> mode();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// 新しいクライアントを作成（秘密鍵から）
  static Future<MeisoNostrClient> newInstance({required String secretKeyHex, required List<String> relays}) =>
      RustLib.instance.api.crateApiMeisoNostrClientNew(secretKeyHex: secretKeyHex, relays: relays);

  /// 新しいクライアントを作成（Amberモード - 公開鍵のみ）
  /// 後方互換性のため残す
  static Future<MeisoNostrClient> newAmberMode({
    required String publicKeyHex,
    required List<String> relays,
    String? proxyUrl,
  }) => RustLib.instance.api.crateApiMeisoNostrClientNewAmberMode(
    publicKeyHex: publicKeyHex,
    relays: relays,
    proxyUrl: proxyUrl,
  );

  /// 新しいクライアントを作成（Amberモード - 公開鍵のみ、Torモード指定）
  static Future<MeisoNostrClient> newAmberModeWithTor({
    required String publicKeyHex,
    required List<String> relays,
    required TorMode torMode,
    String? proxyUrl,
  }) => RustLib.instance.api.crateApiMeisoNostrClientNewAmberModeWithTor(
    publicKeyHex: publicKeyHex,
    relays: relays,
    torMode: torMode,
    proxyUrl: proxyUrl,
  );

  /// 新しいクライアントを作成（秘密鍵 + プロキシオプション）
  /// 後方互換性のため残す
  static Future<MeisoNostrClient> newWithProxy({
    required String secretKeyHex,
    required List<String> relays,
    String? proxyUrl,
  }) => RustLib.instance.api.crateApiMeisoNostrClientNewWithProxy(
    secretKeyHex: secretKeyHex,
    relays: relays,
    proxyUrl: proxyUrl,
  );

  /// 新しいクライアントを作成（Torモード指定）
  static Future<MeisoNostrClient> newWithTorMode({
    required String secretKeyHex,
    required List<String> relays,
    required TorMode torMode,
    String? proxyUrl,
  }) => RustLib.instance.api.crateApiMeisoNostrClientNewWithTorMode(
    secretKeyHex: secretKeyHex,
    relays: relays,
    torMode: torMode,
    proxyUrl: proxyUrl,
  );

  /// 公開鍵を取得（hex形式）
  Future<String> publicKeyHex();

  /// 公開鍵を取得（npub形式）
  Future<String> publicKeyNpub();

  /// リレーリストをNostrに保存（NIP-65 Kind 10002 - Relay List Metadata）
  Future<EventSendResult> saveRelayList({required List<String> relays});

  /// アプリ設定をNostrから同期（Kind 30078）
  Future<AppSettings?> syncAppSettings();

  /// リレーリストをNostrから同期（NIP-65 Kind 10002）
  Future<List<String>> syncRelayList();

  /// TodoリストをNostrから同期（Kind 30001）
  /// すべてのリスト（デフォルト + カスタムリスト）から取得
  Future<List<TodoData>> syncTodoList();

  /// TodoリストをNostrから差分同期（Kind 30001）
  ///
  /// - `since` が 0 より大きい場合、そのUNIX秒以降のイベントのみ取得
  /// - 同じ d tag の中で最新（created_at最大）のイベントのみ処理
  ///
  /// Note:
  /// - replaceable event の特性上、差分でも「変更のあったリストの全内容」は取得される。
  /// - `since` 以降にイベントが無い場合は空Vecを返す（= 変更なし）。
  Future<List<TodoData>> syncTodoListSince({required PlatformInt64 since, required BigInt timeoutSecs});

  /// リレーリストを動的に更新（既存の接続を維持しつつ追加・削除）
  Future<void> updateRelayList({required List<String> newRelays});
}

/// アプリ設定データ構造（NIP-78 Application-specific data - Kind 30078）
class AppSettings {
  /// ダークモード設定
  final bool darkMode;

  /// 週の開始曜日 (0=日曜, 1=月曜, ...)
  final int weekStartDay;

  /// カレンダー表示形式 ("week" | "month")
  final String calendarView;

  /// 通知設定
  final bool notificationsEnabled;

  /// リレーリスト（NIP-65 kind 10002から同期）
  final List<String> relays;

  /// Tor接続モード
  final TorMode torMode;

  /// プロキシURL（Orbotモード使用時、通常は socks5://127.0.0.1:9050）
  final String proxyUrl;

  /// カスタムリストの順番（リストIDの配列）
  final List<String> customListOrder;

  /// 最後に見ていたカスタムリストID
  final String? lastViewedCustomListId;

  /// NIP-89 `client` タグを付与する（false = オプトアウト、既定 true）
  final bool nip89ClientTagEnabled;

  /// 最終更新日時
  final String updatedAt;

  const AppSettings({
    required this.darkMode,
    required this.weekStartDay,
    required this.calendarView,
    required this.notificationsEnabled,
    required this.relays,
    required this.torMode,
    required this.proxyUrl,
    required this.customListOrder,
    this.lastViewedCustomListId,
    required this.nip89ClientTagEnabled,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      darkMode.hashCode ^
      weekStartDay.hashCode ^
      calendarView.hashCode ^
      notificationsEnabled.hashCode ^
      relays.hashCode ^
      torMode.hashCode ^
      proxyUrl.hashCode ^
      customListOrder.hashCode ^
      lastViewedCustomListId.hashCode ^
      nip89ClientTagEnabled.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettings &&
          runtimeType == other.runtimeType &&
          darkMode == other.darkMode &&
          weekStartDay == other.weekStartDay &&
          calendarView == other.calendarView &&
          notificationsEnabled == other.notificationsEnabled &&
          relays == other.relays &&
          torMode == other.torMode &&
          proxyUrl == other.proxyUrl &&
          customListOrder == other.customListOrder &&
          lastViewedCustomListId == other.lastViewedCustomListId &&
          nip89ClientTagEnabled == other.nip89ClientTagEnabled &&
          updatedAt == other.updatedAt;
}

/// キャッシュされたイベント情報（Hive保存用）
class CachedEventInfo {
  /// イベントID
  final String eventId;

  /// イベントの種類
  final BigInt kind;

  /// イベント作成日時（UNIX timestamp）
  final PlatformInt64 createdAt;

  /// イベント内容（JSON文字列）
  final String eventJson;

  /// キャッシュされた日時（UNIX timestamp）
  final PlatformInt64 cachedAt;

  /// TTL（秒）
  final BigInt ttlSeconds;

  /// d-tag（Replaceable eventの場合）
  final String? dTag;

  const CachedEventInfo({
    required this.eventId,
    required this.kind,
    required this.createdAt,
    required this.eventJson,
    required this.cachedAt,
    required this.ttlSeconds,
    this.dTag,
  });

  /// キャッシュが有効かチェック
  Future<bool> isValid() => RustLib.instance.api.crateApiCachedEventInfoIsValid(
    that: this,
  );

  @override
  int get hashCode =>
      eventId.hashCode ^
      kind.hashCode ^
      createdAt.hashCode ^
      eventJson.hashCode ^
      cachedAt.hashCode ^
      ttlSeconds.hashCode ^
      dTag.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CachedEventInfo &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          kind == other.kind &&
          createdAt == other.createdAt &&
          eventJson == other.eventJson &&
          cachedAt == other.cachedAt &&
          ttlSeconds == other.ttlSeconds &&
          dTag == other.dTag;
}

/// 暗号化されたアプリ設定イベントを取得（Amber復号化用）
class EncryptedAppSettingsEvent {
  final String eventId;
  final String encryptedContent;
  final PlatformInt64 createdAt;

  const EncryptedAppSettingsEvent({
    required this.eventId,
    required this.encryptedContent,
    required this.createdAt,
  });

  @override
  int get hashCode => eventId.hashCode ^ encryptedContent.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptedAppSettingsEvent &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          encryptedContent == other.encryptedContent &&
          createdAt == other.createdAt;
}

/// 暗号化されたグループタスクイベント（Amber復号化用）
class EncryptedGroupTodoListEvent {
  final String eventId;
  final String encryptedContent;
  final PlatformInt64 createdAt;
  final String listId;
  final String? groupName;
  final String encryptedData;
  final List<String> members;
  final List<EncryptedKeyData> encryptedKeys;

  const EncryptedGroupTodoListEvent({
    required this.eventId,
    required this.encryptedContent,
    required this.createdAt,
    required this.listId,
    this.groupName,
    required this.encryptedData,
    required this.members,
    required this.encryptedKeys,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      encryptedContent.hashCode ^
      createdAt.hashCode ^
      listId.hashCode ^
      groupName.hashCode ^
      encryptedData.hashCode ^
      members.hashCode ^
      encryptedKeys.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptedGroupTodoListEvent &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          encryptedContent == other.encryptedContent &&
          createdAt == other.createdAt &&
          listId == other.listId &&
          groupName == other.groupName &&
          encryptedData == other.encryptedData &&
          members == other.members &&
          encryptedKeys == other.encryptedKeys;
}

/// メンバー用に暗号化されたAES鍵（Flutter互換）
class EncryptedKeyData {
  final String memberPubkey;
  final String encryptedAesKey;

  const EncryptedKeyData({
    required this.memberPubkey,
    required this.encryptedAesKey,
  });

  @override
  int get hashCode => memberPubkey.hashCode ^ encryptedAesKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptedKeyData &&
          runtimeType == other.runtimeType &&
          memberPubkey == other.memberPubkey &&
          encryptedAesKey == other.encryptedAesKey;
}

/// 公開鍵だけで暗号化されたTodoイベントを取得（Amber復号化用 - 旧実装 Kind 30078）
/// 復号化はAmber側で行うため、暗号化されたままのイベントを返す
class EncryptedTodoEvent {
  final String eventId;
  final String encryptedContent;
  final PlatformInt64 createdAt;
  final String dTag;

  const EncryptedTodoEvent({
    required this.eventId,
    required this.encryptedContent,
    required this.createdAt,
    required this.dTag,
  });

  @override
  int get hashCode => eventId.hashCode ^ encryptedContent.hashCode ^ createdAt.hashCode ^ dTag.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptedTodoEvent &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          encryptedContent == other.encryptedContent &&
          createdAt == other.createdAt &&
          dTag == other.dTag;
}

/// 暗号化されたTodoリストイベントを取得（Amber復号化用 - Kind 30001）
class EncryptedTodoListEvent {
  final String eventId;
  final String encryptedContent;
  final PlatformInt64 createdAt;

  /// リスト識別子（d tag）
  final String? listId;

  /// リスト名（title tag）
  final String? title;

  const EncryptedTodoListEvent({
    required this.eventId,
    required this.encryptedContent,
    required this.createdAt,
    this.listId,
    this.title,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^ encryptedContent.hashCode ^ createdAt.hashCode ^ listId.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptedTodoListEvent &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          encryptedContent == other.encryptedContent &&
          createdAt == other.createdAt &&
          listId == other.listId &&
          title == other.title;
}

/// イベント送信結果
class EventSendResult {
  /// イベントID
  final String eventId;

  /// 送信成功したか
  final bool success;

  /// 成功したリレー数
  final BigInt successfulRelays;

  /// 失敗したリレー数
  final BigInt failedRelays;

  /// タイムアウトしたか
  final bool timedOut;

  /// エラーメッセージ（失敗時）
  final String? errorMessage;

  const EventSendResult({
    required this.eventId,
    required this.success,
    required this.successfulRelays,
    required this.failedRelays,
    required this.timedOut,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      success.hashCode ^
      successfulRelays.hashCode ^
      failedRelays.hashCode ^
      timedOut.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventSendResult &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          success == other.success &&
          successfulRelays == other.successfulRelays &&
          failedRelays == other.failedRelays &&
          timedOut == other.timedOut &&
          errorMessage == other.errorMessage;
}

/// 鍵ペアを生成（nsec/npub形式で返す）
class KeyPair {
  final String privateKeyNsec;
  final String publicKeyNpub;
  final String privateKeyHex;
  final String publicKeyHex;

  const KeyPair({
    required this.privateKeyNsec,
    required this.publicKeyNpub,
    required this.privateKeyHex,
    required this.publicKeyHex,
  });

  @override
  int get hashCode => privateKeyNsec.hashCode ^ publicKeyNpub.hashCode ^ privateKeyHex.hashCode ^ publicKeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyPair &&
          runtimeType == other.runtimeType &&
          privateKeyNsec == other.privateKeyNsec &&
          publicKeyNpub == other.publicKeyNpub &&
          privateKeyHex == other.privateKeyHex &&
          publicKeyHex == other.publicKeyHex;
}

/// Subscription経由で受信したイベント
class ReceivedEvent {
  /// イベントID
  final String eventId;

  /// イベントの種類
  final BigInt kind;

  /// イベント作成日時
  final PlatformInt64 createdAt;

  /// イベント内容（JSON文字列）
  final String eventJson;

  /// 受信日時
  final PlatformInt64 receivedAt;

  /// Subscription ID
  final String subscriptionId;

  const ReceivedEvent({
    required this.eventId,
    required this.kind,
    required this.createdAt,
    required this.eventJson,
    required this.receivedAt,
    required this.subscriptionId,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      kind.hashCode ^
      createdAt.hashCode ^
      eventJson.hashCode ^
      receivedAt.hashCode ^
      subscriptionId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceivedEvent &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          kind == other.kind &&
          createdAt == other.createdAt &&
          eventJson == other.eventJson &&
          receivedAt == other.receivedAt &&
          subscriptionId == other.subscriptionId;
}

/// Subscription情報
class SubscriptionInfo {
  /// Subscription ID
  final String subscriptionId;

  /// フィルター（JSON形式）
  final String filtersJson;

  /// 作成日時
  final PlatformInt64 createdAt;

  const SubscriptionInfo({
    required this.subscriptionId,
    required this.filtersJson,
    required this.createdAt,
  });

  @override
  int get hashCode => subscriptionId.hashCode ^ filtersJson.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubscriptionInfo &&
          runtimeType == other.runtimeType &&
          subscriptionId == other.subscriptionId &&
          filtersJson == other.filtersJson &&
          createdAt == other.createdAt;
}

/// Todoデータ構造（Flutter側と同期）
class TodoData {
  final String id;
  final String title;
  final bool completed;
  final String? date;
  final int order;
  final String createdAt;
  final String updatedAt;
  final String? eventId;
  final String? linkPreview;
  final String? recurrence;
  final String? parentRecurringId;
  final String? customListId;

  /// 親タスクID（サブタスク関係、NIP-XXA "parent" tag 互換）
  final String? parentTaskId;

  /// ネスト深度（0 = ルート）
  final int depth;

  /// タスクリンク（JSON文字列: [{targetTaskId, linkType}, ...]）
  final String? taskLinks;

  /// 添付画像URL（Blossom/NIP-96経由）
  final String? imageUrl;

  const TodoData({
    required this.id,
    required this.title,
    required this.completed,
    this.date,
    required this.order,
    required this.createdAt,
    required this.updatedAt,
    this.eventId,
    this.linkPreview,
    this.recurrence,
    this.parentRecurringId,
    this.customListId,
    this.parentTaskId,
    required this.depth,
    this.taskLinks,
    this.imageUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      completed.hashCode ^
      date.hashCode ^
      order.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      eventId.hashCode ^
      linkPreview.hashCode ^
      recurrence.hashCode ^
      parentRecurringId.hashCode ^
      customListId.hashCode ^
      parentTaskId.hashCode ^
      depth.hashCode ^
      taskLinks.hashCode ^
      imageUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          completed == other.completed &&
          date == other.date &&
          order == other.order &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          eventId == other.eventId &&
          linkPreview == other.linkPreview &&
          recurrence == other.recurrence &&
          parentRecurringId == other.parentRecurringId &&
          customListId == other.customListId &&
          parentTaskId == other.parentTaskId &&
          depth == other.depth &&
          taskLinks == other.taskLinks &&
          imageUrl == other.imageUrl;
}

/// Todoリストのメタデータ（通常モード用 - Kind 30001）
class TodoListMetadata {
  final String eventId;
  final PlatformInt64 createdAt;

  /// リスト識別子（d tag）
  final String? listId;

  /// リスト名（title tag）
  final String? title;

  const TodoListMetadata({
    required this.eventId,
    required this.createdAt,
    this.listId,
    this.title,
  });

  @override
  int get hashCode => eventId.hashCode ^ createdAt.hashCode ^ listId.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoListMetadata &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          createdAt == other.createdAt &&
          listId == other.listId &&
          title == other.title;
}

/// すべてのTodoリスト（デフォルト + カスタムリスト）を取得
/// Phase 8.5.2: カスタムリスト名のみを取得（軽量版）
///
/// contentを解析せず、タグ（d, title）のみを返すため高速
/// Issue #101: event_idを追加して削除済みイベントのフィルタリングを可能にする
/// Zombie List Fix: created_atを追加してLWW比較を可能にする
class TodoListName {
  final String listId;
  final String? title;
  final String eventId;
  final BigInt createdAt;

  const TodoListName({
    required this.listId,
    this.title,
    required this.eventId,
    required this.createdAt,
  });

  @override
  int get hashCode => listId.hashCode ^ title.hashCode ^ eventId.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoListName &&
          runtimeType == other.runtimeType &&
          listId == other.listId &&
          title == other.title &&
          eventId == other.eventId &&
          createdAt == other.createdAt;
}

/// Tor接続モード
enum TorMode {
  /// Tor無効（直接接続）
  disabled,

  /// 内蔵Tor (Embedded Tor)
  internal,

  /// Orbot経由 (SOCKS5 Proxy)
  orbot;

  static Future<TorMode> default_() => RustLib.instance.api.crateApiTorModeDefault();
}
