// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Nostrクライアントを初期化（hex公開鍵を返す）
Future<String> initNostrClient({required String secretKeyHex, required List<String> relays}) =>
    RustLib.instance.api.crateApiInitNostrClient(secretKeyHex: secretKeyHex, relays: relays);

/// 公開鍵をnpub形式で取得
Future<String> getPublicKeyNpub() => RustLib.instance.api.crateApiGetPublicKeyNpub();

/// 新しい秘密鍵を生成
Future<String> generateSecretKey() => RustLib.instance.api.crateApiGenerateSecretKey();

/// Todoを作成
Future<String> createTodo({required TodoData todo}) => RustLib.instance.api.crateApiCreateTodo(todo: todo);

/// Todoを更新
Future<String> updateTodo({required TodoData todo}) => RustLib.instance.api.crateApiUpdateTodo(todo: todo);

/// Todoを削除
Future<void> deleteTodo({required String todoId}) => RustLib.instance.api.crateApiDeleteTodo(todoId: todoId);

/// 全Todoを同期
Future<List<TodoData>> syncTodos() => RustLib.instance.api.crateApiSyncTodos();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MeisoNostrClient>>
abstract class MeisoNostrClient implements RustOpaqueInterface {
  /// TodoをNostrイベントとして作成
  Future<String> createTodo({required TodoData todo});

  /// Todoを削除（削除イベント送信）
  Future<void> deleteTodo({required String todoId});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// 新しいクライアントを作成（秘密鍵から）
  static Future<MeisoNostrClient> newInstance({required String secretKeyHex, required List<String> relays}) =>
      RustLib.instance.api.crateApiMeisoNostrClientNew(secretKeyHex: secretKeyHex, relays: relays);

  /// 公開鍵を取得（hex形式）
  Future<String> publicKeyHex();

  /// 公開鍵を取得（npub形式）
  Future<String> publicKeyNpub();

  /// 全てのTodoを同期（リレーから取得）
  Future<List<TodoData>> syncTodos();

  /// Todoを更新（既存イベントを置き換え）
  Future<String> updateTodo({required TodoData todo});
}

/// Todoデータ構造（Flutter側と同期）
class TodoData {
  final String id;
  final String title;
  final bool completed;
  final String? date;
  final int order;
  final String createdAt;
  final String updatedAt;
  final String? eventId;

  const TodoData({
    required this.id,
    required this.title,
    required this.completed,
    this.date,
    required this.order,
    required this.createdAt,
    required this.updatedAt,
    this.eventId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      completed.hashCode ^
      date.hashCode ^
      order.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      eventId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          completed == other.completed &&
          date == other.date &&
          order == other.order &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          eventId == other.eventId;
}
