// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'group_tasks.dart';
import 'group_tasks_mls.dart';
import 'group_tasks_shared.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MeisoNostrClientPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClientPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  MeisoNostrClient dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClient(
    dynamic raw,
  );

  @protected
  MeisoNostrClient dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClient(
    dynamic raw,
  );

  @protected
  MeisoNostrClient dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClient(
    dynamic raw,
  );

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppSettings dco_decode_app_settings(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AppSettings dco_decode_box_autoadd_app_settings(dynamic raw);

  @protected
  CachedEventInfo dco_decode_box_autoadd_cached_event_info(dynamic raw);

  @protected
  EncryptedAppSettingsEvent dco_decode_box_autoadd_encrypted_app_settings_event(dynamic raw);

  @protected
  EncryptedTodoListEvent dco_decode_box_autoadd_encrypted_todo_list_event(dynamic raw);

  @protected
  GroupTodoList dco_decode_box_autoadd_group_todo_list(dynamic raw);

  @protected
  KeyPackageResult dco_decode_box_autoadd_key_package_result(dynamic raw);

  @protected
  CachedEventInfo dco_decode_cached_event_info(dynamic raw);

  @protected
  ContactProfile dco_decode_contact_profile(dynamic raw);

  @protected
  EncryptedAppSettingsEvent dco_decode_encrypted_app_settings_event(dynamic raw);

  @protected
  EncryptedGroupTodoListEvent dco_decode_encrypted_group_todo_list_event(dynamic raw);

  @protected
  EncryptedKey dco_decode_encrypted_key(dynamic raw);

  @protected
  EncryptedKeyData dco_decode_encrypted_key_data(dynamic raw);

  @protected
  EncryptedTodoEvent dco_decode_encrypted_todo_event(dynamic raw);

  @protected
  EncryptedTodoListEvent dco_decode_encrypted_todo_list_event(dynamic raw);

  @protected
  EventSendResult dco_decode_event_send_result(dynamic raw);

  @protected
  GroupKey dco_decode_group_key(dynamic raw);

  @protected
  GroupTodoData dco_decode_group_todo_data(dynamic raw);

  @protected
  GroupTodoList dco_decode_group_todo_list(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  InvitationPayload dco_decode_invitation_payload(dynamic raw);

  @protected
  KeyPackageResult dco_decode_key_package_result(dynamic raw);

  @protected
  KeyPair dco_decode_key_pair(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ContactProfile> dco_decode_list_contact_profile(dynamic raw);

  @protected
  List<EncryptedGroupTodoListEvent> dco_decode_list_encrypted_group_todo_list_event(dynamic raw);

  @protected
  List<EncryptedKey> dco_decode_list_encrypted_key(dynamic raw);

  @protected
  List<EncryptedKeyData> dco_decode_list_encrypted_key_data(dynamic raw);

  @protected
  List<EncryptedTodoEvent> dco_decode_list_encrypted_todo_event(dynamic raw);

  @protected
  List<EncryptedTodoListEvent> dco_decode_list_encrypted_todo_list_event(dynamic raw);

  @protected
  List<GroupTodoData> dco_decode_list_group_todo_data(dynamic raw);

  @protected
  List<GroupTodoList> dco_decode_list_group_todo_list(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ReceivedEvent> dco_decode_list_received_event(dynamic raw);

  @protected
  List<(String, BigInt)> dco_decode_list_record_string_u_64(dynamic raw);

  @protected
  List<RelayStatusInfo> dco_decode_list_relay_status_info(dynamic raw);

  @protected
  List<TodoData> dco_decode_list_todo_data(dynamic raw);

  @protected
  List<TodoListMetadata> dco_decode_list_todo_list_metadata(dynamic raw);

  @protected
  List<TodoListName> dco_decode_list_todo_list_name(dynamic raw);

  @protected
  MlsGroupInfo dco_decode_mls_group_info(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AppSettings? dco_decode_opt_box_autoadd_app_settings(dynamic raw);

  @protected
  EncryptedAppSettingsEvent? dco_decode_opt_box_autoadd_encrypted_app_settings_event(dynamic raw);

  @protected
  EncryptedTodoListEvent? dco_decode_opt_box_autoadd_encrypted_todo_list_event(dynamic raw);

  @protected
  ReceivedEvent dco_decode_received_event(dynamic raw);

  @protected
  (String, String, String, String, String) dco_decode_record_string_string_string_string_string(dynamic raw);

  @protected
  (String, BigInt) dco_decode_record_string_u_64(dynamic raw);

  @protected
  RelayConnectionInfo dco_decode_relay_connection_info(dynamic raw);

  @protected
  RelayStatusInfo dco_decode_relay_status_info(dynamic raw);

  @protected
  SubscriptionInfo dco_decode_subscription_info(dynamic raw);

  @protected
  TodoData dco_decode_todo_data(dynamic raw);

  @protected
  TodoListMetadata dco_decode_todo_list_metadata(dynamic raw);

  @protected
  TodoListName dco_decode_todo_list_name(dynamic raw);

  @protected
  TorMode dco_decode_tor_mode(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  MeisoNostrClient sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClient(
    SseDeserializer deserializer,
  );

  @protected
  MeisoNostrClient sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClient(
    SseDeserializer deserializer,
  );

  @protected
  MeisoNostrClient sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClient(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_app_settings(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_box_autoadd_app_settings(SseDeserializer deserializer);

  @protected
  CachedEventInfo sse_decode_box_autoadd_cached_event_info(SseDeserializer deserializer);

  @protected
  EncryptedAppSettingsEvent sse_decode_box_autoadd_encrypted_app_settings_event(SseDeserializer deserializer);

  @protected
  EncryptedTodoListEvent sse_decode_box_autoadd_encrypted_todo_list_event(SseDeserializer deserializer);

  @protected
  GroupTodoList sse_decode_box_autoadd_group_todo_list(SseDeserializer deserializer);

  @protected
  KeyPackageResult sse_decode_box_autoadd_key_package_result(SseDeserializer deserializer);

  @protected
  CachedEventInfo sse_decode_cached_event_info(SseDeserializer deserializer);

  @protected
  ContactProfile sse_decode_contact_profile(SseDeserializer deserializer);

  @protected
  EncryptedAppSettingsEvent sse_decode_encrypted_app_settings_event(SseDeserializer deserializer);

  @protected
  EncryptedGroupTodoListEvent sse_decode_encrypted_group_todo_list_event(SseDeserializer deserializer);

  @protected
  EncryptedKey sse_decode_encrypted_key(SseDeserializer deserializer);

  @protected
  EncryptedKeyData sse_decode_encrypted_key_data(SseDeserializer deserializer);

  @protected
  EncryptedTodoEvent sse_decode_encrypted_todo_event(SseDeserializer deserializer);

  @protected
  EncryptedTodoListEvent sse_decode_encrypted_todo_list_event(SseDeserializer deserializer);

  @protected
  EventSendResult sse_decode_event_send_result(SseDeserializer deserializer);

  @protected
  GroupKey sse_decode_group_key(SseDeserializer deserializer);

  @protected
  GroupTodoData sse_decode_group_todo_data(SseDeserializer deserializer);

  @protected
  GroupTodoList sse_decode_group_todo_list(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  InvitationPayload sse_decode_invitation_payload(SseDeserializer deserializer);

  @protected
  KeyPackageResult sse_decode_key_package_result(SseDeserializer deserializer);

  @protected
  KeyPair sse_decode_key_pair(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ContactProfile> sse_decode_list_contact_profile(SseDeserializer deserializer);

  @protected
  List<EncryptedGroupTodoListEvent> sse_decode_list_encrypted_group_todo_list_event(SseDeserializer deserializer);

  @protected
  List<EncryptedKey> sse_decode_list_encrypted_key(SseDeserializer deserializer);

  @protected
  List<EncryptedKeyData> sse_decode_list_encrypted_key_data(SseDeserializer deserializer);

  @protected
  List<EncryptedTodoEvent> sse_decode_list_encrypted_todo_event(SseDeserializer deserializer);

  @protected
  List<EncryptedTodoListEvent> sse_decode_list_encrypted_todo_list_event(SseDeserializer deserializer);

  @protected
  List<GroupTodoData> sse_decode_list_group_todo_data(SseDeserializer deserializer);

  @protected
  List<GroupTodoList> sse_decode_list_group_todo_list(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ReceivedEvent> sse_decode_list_received_event(SseDeserializer deserializer);

  @protected
  List<(String, BigInt)> sse_decode_list_record_string_u_64(SseDeserializer deserializer);

  @protected
  List<RelayStatusInfo> sse_decode_list_relay_status_info(SseDeserializer deserializer);

  @protected
  List<TodoData> sse_decode_list_todo_data(SseDeserializer deserializer);

  @protected
  List<TodoListMetadata> sse_decode_list_todo_list_metadata(SseDeserializer deserializer);

  @protected
  List<TodoListName> sse_decode_list_todo_list_name(SseDeserializer deserializer);

  @protected
  MlsGroupInfo sse_decode_mls_group_info(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AppSettings? sse_decode_opt_box_autoadd_app_settings(SseDeserializer deserializer);

  @protected
  EncryptedAppSettingsEvent? sse_decode_opt_box_autoadd_encrypted_app_settings_event(SseDeserializer deserializer);

  @protected
  EncryptedTodoListEvent? sse_decode_opt_box_autoadd_encrypted_todo_list_event(SseDeserializer deserializer);

  @protected
  ReceivedEvent sse_decode_received_event(SseDeserializer deserializer);

  @protected
  (String, String, String, String, String) sse_decode_record_string_string_string_string_string(
    SseDeserializer deserializer,
  );

  @protected
  (String, BigInt) sse_decode_record_string_u_64(SseDeserializer deserializer);

  @protected
  RelayConnectionInfo sse_decode_relay_connection_info(SseDeserializer deserializer);

  @protected
  RelayStatusInfo sse_decode_relay_status_info(SseDeserializer deserializer);

  @protected
  SubscriptionInfo sse_decode_subscription_info(SseDeserializer deserializer);

  @protected
  TodoData sse_decode_todo_data(SseDeserializer deserializer);

  @protected
  TodoListMetadata sse_decode_todo_list_metadata(SseDeserializer deserializer);

  @protected
  TodoListName sse_decode_todo_list_name(SseDeserializer deserializer);

  @protected
  TorMode sse_decode_tor_mode(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClient(
    MeisoNostrClient self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClient(
    MeisoNostrClient self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClient(
    MeisoNostrClient self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(RustStreamSink<String> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_settings(AppSettings self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_settings(AppSettings self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_cached_event_info(CachedEventInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_encrypted_app_settings_event(EncryptedAppSettingsEvent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_encrypted_todo_list_event(EncryptedTodoListEvent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_group_todo_list(GroupTodoList self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_key_package_result(KeyPackageResult self, SseSerializer serializer);

  @protected
  void sse_encode_cached_event_info(CachedEventInfo self, SseSerializer serializer);

  @protected
  void sse_encode_contact_profile(ContactProfile self, SseSerializer serializer);

  @protected
  void sse_encode_encrypted_app_settings_event(EncryptedAppSettingsEvent self, SseSerializer serializer);

  @protected
  void sse_encode_encrypted_group_todo_list_event(EncryptedGroupTodoListEvent self, SseSerializer serializer);

  @protected
  void sse_encode_encrypted_key(EncryptedKey self, SseSerializer serializer);

  @protected
  void sse_encode_encrypted_key_data(EncryptedKeyData self, SseSerializer serializer);

  @protected
  void sse_encode_encrypted_todo_event(EncryptedTodoEvent self, SseSerializer serializer);

  @protected
  void sse_encode_encrypted_todo_list_event(EncryptedTodoListEvent self, SseSerializer serializer);

  @protected
  void sse_encode_event_send_result(EventSendResult self, SseSerializer serializer);

  @protected
  void sse_encode_group_key(GroupKey self, SseSerializer serializer);

  @protected
  void sse_encode_group_todo_data(GroupTodoData self, SseSerializer serializer);

  @protected
  void sse_encode_group_todo_list(GroupTodoList self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_invitation_payload(InvitationPayload self, SseSerializer serializer);

  @protected
  void sse_encode_key_package_result(KeyPackageResult self, SseSerializer serializer);

  @protected
  void sse_encode_key_pair(KeyPair self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_contact_profile(List<ContactProfile> self, SseSerializer serializer);

  @protected
  void sse_encode_list_encrypted_group_todo_list_event(
    List<EncryptedGroupTodoListEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_encrypted_key(List<EncryptedKey> self, SseSerializer serializer);

  @protected
  void sse_encode_list_encrypted_key_data(List<EncryptedKeyData> self, SseSerializer serializer);

  @protected
  void sse_encode_list_encrypted_todo_event(List<EncryptedTodoEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_list_encrypted_todo_list_event(List<EncryptedTodoListEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_list_group_todo_data(List<GroupTodoData> self, SseSerializer serializer);

  @protected
  void sse_encode_list_group_todo_list(List<GroupTodoList> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_received_event(List<ReceivedEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_u_64(List<(String, BigInt)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_relay_status_info(List<RelayStatusInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_todo_data(List<TodoData> self, SseSerializer serializer);

  @protected
  void sse_encode_list_todo_list_metadata(List<TodoListMetadata> self, SseSerializer serializer);

  @protected
  void sse_encode_list_todo_list_name(List<TodoListName> self, SseSerializer serializer);

  @protected
  void sse_encode_mls_group_info(MlsGroupInfo self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_app_settings(AppSettings? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_encrypted_app_settings_event(
    EncryptedAppSettingsEvent? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_encrypted_todo_list_event(EncryptedTodoListEvent? self, SseSerializer serializer);

  @protected
  void sse_encode_received_event(ReceivedEvent self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string_string_string_string(
    (String, String, String, String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_u_64((String, BigInt) self, SseSerializer serializer);

  @protected
  void sse_encode_relay_connection_info(RelayConnectionInfo self, SseSerializer serializer);

  @protected
  void sse_encode_relay_status_info(RelayStatusInfo self, SseSerializer serializer);

  @protected
  void sse_encode_subscription_info(SubscriptionInfo self, SseSerializer serializer);

  @protected
  void sse_encode_todo_data(TodoData self, SseSerializer serializer);

  @protected
  void sse_encode_todo_list_metadata(TodoListMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_todo_list_name(TodoListName self, SseSerializer serializer);

  @protected
  void sse_encode_tor_mode(TorMode self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) => RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClient(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClient(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_meiso_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClient',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClient =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClient(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClient(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_meiso_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClient',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClient =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeisoNostrClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
