// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Result type for key package creation
class KeyPackageResult {
  final String keyPackage;
  final String mlsProtocolVersion;
  final String ciphersuite;
  final String extensions;

  const KeyPackageResult({
    required this.keyPackage,
    required this.mlsProtocolVersion,
    required this.ciphersuite,
    required this.extensions,
  });

  @override
  int get hashCode => keyPackage.hashCode ^ mlsProtocolVersion.hashCode ^ ciphersuite.hashCode ^ extensions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyPackageResult &&
          runtimeType == other.runtimeType &&
          keyPackage == other.keyPackage &&
          mlsProtocolVersion == other.mlsProtocolVersion &&
          ciphersuite == other.ciphersuite &&
          extensions == other.extensions;
}

/// Result type for MLS group info
class MlsGroupInfo {
  final String groupId;
  final String groupName;
  final List<String> memberPubkeys;
  final BigInt epoch;

  const MlsGroupInfo({
    required this.groupId,
    required this.groupName,
    required this.memberPubkeys,
    required this.epoch,
  });

  @override
  int get hashCode => groupId.hashCode ^ groupName.hashCode ^ memberPubkeys.hashCode ^ epoch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MlsGroupInfo &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          groupName == other.groupName &&
          memberPubkeys == other.memberPubkeys &&
          epoch == other.epoch;
}
