// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 新規生成されたグループ鍵
class GroupKey {
  /// 秘密鍵(hex)。メンバー間で共有される共有秘密。ログ出力厳禁。
  final String nsecHex;

  /// 公開鍵(hex)。タスクイベントの author になる。
  final String npubHex;

  const GroupKey({
    required this.nsecHex,
    required this.npubHex,
  });

  @override
  int get hashCode => nsecHex.hashCode ^ npubHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupKey && runtimeType == other.runtimeType && nsecHex == other.nsecHex && npubHex == other.npubHex;
}

/// 招待 payload(NIP-44 で封緘される平文)
class InvitationPayload {
  final String groupId;

  /// グループ秘密鍵(hex)
  final String groupNsec;

  /// グループ公開鍵(hex)。タスク購読の author フィルタに使用。
  final String groupNpub;
  final String groupName;
  final BigInt keyEpoch;

  const InvitationPayload({
    required this.groupId,
    required this.groupNsec,
    required this.groupNpub,
    required this.groupName,
    required this.keyEpoch,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^ groupNsec.hashCode ^ groupNpub.hashCode ^ groupName.hashCode ^ keyEpoch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InvitationPayload &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          groupNsec == other.groupNsec &&
          groupNpub == other.groupNpub &&
          groupName == other.groupName &&
          keyEpoch == other.keyEpoch;
}
