// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// メンバー用に暗号化されたAES鍵
class EncryptedKey {
  final String memberPubkey;
  final String encryptedAesKey;

  const EncryptedKey({
    required this.memberPubkey,
    required this.encryptedAesKey,
  });

  @override
  int get hashCode => memberPubkey.hashCode ^ encryptedAesKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptedKey &&
          runtimeType == other.runtimeType &&
          memberPubkey == other.memberPubkey &&
          encryptedAesKey == other.encryptedAesKey;
}

/// グループタスクデータ（暗号化前）
class GroupTodoData {
  final String id;
  final String title;
  final bool completed;
  final String? date;
  final int order;
  final String createdAt;
  final String updatedAt;

  const GroupTodoData({
    required this.id,
    required this.title,
    required this.completed,
    this.date,
    required this.order,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      completed.hashCode ^
      date.hashCode ^
      order.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupTodoData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          completed == other.completed &&
          date == other.date &&
          order == other.order &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// 暗号化されたグループタスクリスト
class GroupTodoList {
  final String groupId;
  final String groupName;
  final String encryptedData;
  final List<String> members;
  final List<EncryptedKey> encryptedKeys;

  const GroupTodoList({
    required this.groupId,
    required this.groupName,
    required this.encryptedData,
    required this.members,
    required this.encryptedKeys,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^ groupName.hashCode ^ encryptedData.hashCode ^ members.hashCode ^ encryptedKeys.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupTodoList &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          groupName == other.groupName &&
          encryptedData == other.encryptedData &&
          members == other.members &&
          encryptedKeys == other.encryptedKeys;
}
